# Generated by Django 4.2.1 on 2023-05-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_estudiantes_aporedados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoderados', to='api.estudiantes'),
        ),
    ]
