# Generated by Django 4.2.1 on 2023-05-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_apoderado_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='gradoEstudiante',
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='apellidoApoderado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='celularApoderado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='nombreApoderado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Apoderado',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
