# Generated by Django 4.2.1 on 2023-05-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_mensaje_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apellidoDueño',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombreDueño',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ubicacionCole',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
