# Generated by Django 4.2.1 on 2023-05-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_apellidodueño_customuser_nombredueño_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='apellidoDueño',
            new_name='apellidoDueno',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='nombreDueño',
            new_name='nombreDueno',
        ),
    ]
