# Generated by Django 4.2.1 on 2023-05-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_apellidodueño_customuser_apellidodueno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='fotoEstudiante',
            field=models.ImageField(null=True, upload_to='estudiantes'),
        ),
    ]
