# Generated by Django 4.2.1 on 2023-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_estudiantes_fotoestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='fotoEstudiante',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes'),
        ),
    ]
