# Generated by Django 4.2.1 on 2023-05-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_estudiantes_fotoestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apellidoDueno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nombreDueno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='apellidoApoderado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='celularApoderado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='nombreApoderado',
            field=models.CharField(max_length=100),
        ),
    ]
