# Generated by Django 4.2.1 on 2023-06-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_apellidodueno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmacion',
            field=models.BooleanField(default=False),
        ),
    ]
