# Generated by Django 4.2.1 on 2023-06-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_confirmacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ubicacionCole',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
